{"origin": "/home/a08test/submissions/ahmadar2/a2", "assignment": "a2", "students": [{"last": "Ahmad", "section": "N/A", "first": "Arsalan", "email": "arsalank.ahmad@mail.utoronto.ca", "student_id": "ahmadar2", "source": "N/A", "student_number": "0000000000"}], "results": {"test_all_regex_perms.TestAllRegexPermutations": {"failures": {"test_all_regex_perms.TestAllRegexPermutations.test_long": {"description": "Correctly produces permutations of long regex?", "message": "['(0*.1)*', '0*.(1)*', '*(0.1)*', '0.*(1)[394 chars]).1'] != {'(0.1**)', '(1.0**)', '(0.1)**', '(0.1*)[86 chars].1)'}", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_all_regex_perms.py\", line 50, in test_long\n    self.assertEqual(all_regex_permutations(s), p)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 797, in assertEqual\n    assertion_func(first, second, msg=msg)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 790, in _baseAssertEqual\n    raise self.failureException(msg)\n\nAssertionError: ['(0*.1)*', '0*.(1)*', '*(0.1)*', '0.*(1)[394 chars]).1'] != {'(0.1**)', '(1.0**)', '(0.1)**', '(0.1*)[86 chars].1)'}\n"}, "test_all_regex_perms.TestAllRegexPermutations.test_binary": {"description": "Correctly produces permutations of binary regexes?", "message": "['(0.1)', '0.(1)', '(1.0)', '1.(0)', '(1).0', '(0).1'] != {'(1.0)', '(0.1)'} : Different permutation sets: ['(0.1)', '0.(1)', '(1.0)', '1.(0)', '(1).0', '(0).1'], {'(1.0)', '(0.1)'}", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_all_regex_perms.py\", line 41, in test_binary\n    all_regex_permutations(t[0]), t[1]))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 797, in assertEqual\n    assertion_func(first, second, msg=msg)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 790, in _baseAssertEqual\n    raise self.failureException(msg)\n\nAssertionError: ['(0.1)', '0.(1)', '(1.0)', '1.(0)', '(1).0', '(0).1'] != {'(1.0)', '(0.1)'} : Different permutation sets: ['(0.1)', '0.(1)', '(1.0)', '1.(0)', '(1).0', '(0).1'], {'(1.0)', '(0.1)'}\n"}, "test_all_regex_perms.TestAllRegexPermutations.test_empty_results": {"description": "", "message": "False is not true : No regular expressions can be formed from ||(011) but returned a non-empty collection", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_all_regex_perms.py\", line 22, in test_empty_results\n    \" but returned a non-empty collection\").format(s))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : No regular expressions can be formed from ||(011) but returned a non-empty collection\n"}, "test_all_regex_perms.TestAllRegexPermutations.test_leaf": {"description": "Correctly produces unique permutation of leaf?", "message": "{'e'} != ['e'] : Different permutation set: {'e'}, ['e']", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_all_regex_perms.py\", line 30, in test_leaf\n    set(s), all_regex_permutations(s)))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 797, in assertEqual\n    assertion_func(first, second, msg=msg)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 790, in _baseAssertEqual\n    raise self.failureException(msg)\n\nAssertionError: {'e'} != ['e'] : Different permutation set: {'e'}, ['e']\n"}}}, "test_pep8.TestPEP8": {"passes": {"test_pep8.TestPEP8.test_pep8": ""}}, "test_regex_match.TestRegexMatch": {"passes": {"test_regex_match.TestRegexMatch.test_bar_star_fail": "Correctly rejects near bar-stars?", "test_regex_match.TestRegexMatch.test_dot_bar_fail": "Correctly rejects near dot-bars?", "test_regex_match.TestRegexMatch.test_edge_empty_ok": "Correctly matches various matches of empty string?", "test_regex_match.TestRegexMatch.test_star_okay": "Correctly matches starred regexes?", "test_regex_match.TestRegexMatch.test_leaf_ok": "Correctly matches leaf regexes?"}, "failures": {"test_regex_match.TestRegexMatch.test_dot_fail": {"description": "Correctly rejects near-dots?", "message": "True is not false : Accepts invalid match: (DotTree(Leaf('1'), Leaf('0')), '1')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_regex_match.py\", line 63, in test_dot_fail\n    \"Accepts invalid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid match: (DotTree(Leaf('1'), Leaf('0')), '1')\n"}, "test_regex_match.TestRegexMatch.test_star_fail": {"description": "Correctly rejects near-stars?", "message": "True is not false : Accepts invalid match: (StarTree(Leaf('1')), '1 1')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_regex_match.py\", line 93, in test_star_fail\n    \"Accepts invalid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid match: (StarTree(Leaf('1')), '1 1')\n"}, "test_regex_match.TestRegexMatch.test_dot_star_ok": {"description": "Correctly matches dot-star regexes?", "message": "False is not true : Rejects valid match: (DotTree(StarTree(Leaf('1')), StarTree(Leaf('2'))), '112')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_regex_match.py\", line 123, in test_dot_star_ok\n    \"Rejects valid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid match: (DotTree(StarTree(Leaf('1')), StarTree(Leaf('2'))), '112')\n"}, "test_regex_match.TestRegexMatch.test_bar_star_ok": {"description": "Correctly matches bar-star regexes?", "message": "False is not true : Rejects valid match: (BarTree(StarTree(Leaf('1')), StarTree(Leaf('0'))), '000')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_regex_match.py\", line 139, in test_bar_star_ok\n    \"Rejects valid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid match: (BarTree(StarTree(Leaf('1')), StarTree(Leaf('0'))), '000')\n"}, "test_regex_match.TestRegexMatch.test_bar_star_dot_ok": {"description": "Correctly matches bar-star-dot regexes?", "message": "False is not true : Rejects valid match: (BarTree(StarTree(Leaf('2')), DotTree(Leaf('1'), Leaf('0'))), '10')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_regex_match.py\", line 157, in test_bar_star_dot_ok\n    \"Rejects valid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid match: (BarTree(StarTree(Leaf('2')), DotTree(Leaf('1'), Leaf('0'))), '10')\n"}, "test_regex_match.TestRegexMatch.test_leaf_fail": {"description": "Correct rejects near-leaves?", "message": "True is not false : Accepts invalid match: (Leaf('e'), 'e')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_regex_match.py\", line 38, in test_leaf_fail\n    \"Accepts invalid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid match: (Leaf('e'), 'e')\n"}, "test_regex_match.TestRegexMatch.test_dot_bar_ok": {"description": "Correctly matches dot-bar regexes?", "message": "False is not true : Rejects valid match: (DotTree(BarTree(Leaf('0'), Leaf('1')), BarTree(Leaf('2'), Leaf('0'))), '12')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_regex_match.py\", line 103, in test_dot_bar_ok\n    \"Rejects valid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid match: (DotTree(BarTree(Leaf('0'), Leaf('1')), BarTree(Leaf('2'), Leaf('0'))), '12')\n"}, "test_regex_match.TestRegexMatch.test_dot_okay": {"description": "Correctly matches dotted regexes?", "message": "False is not true : Rejects valid match: (DotTree(Leaf('e'), Leaf('2')), '2')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_regex_match.py\", line 54, in test_dot_okay\n    \"Rejects valid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid match: (DotTree(Leaf('e'), Leaf('2')), '2')\n"}, "test_regex_match.TestRegexMatch.test_difficult_star": {"description": "Correct on difficult case for star (1|(1.2))*?", "message": "False is not true : Rejects valid match: (StarTree(BarTree(Leaf('1'), DotTree(Leaf('1'), Leaf('2')))), '11212')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_regex_match.py\", line 178, in test_difficult_star\n    \"Rejects valid match: {}\".format((r,s)))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid match: (StarTree(BarTree(Leaf('1'), DotTree(Leaf('1'), Leaf('2')))), '11212')\n"}, "test_regex_match.TestRegexMatch.test_dot_star_fail": {"description": "Correctly rejects near dot-stars?", "message": "True is not false : Accepts invalid match: (StarTree(DotTree(Leaf('1'), Leaf('1'))), '111')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_regex_match.py\", line 131, in test_dot_star_fail\n    \"Accepts invalid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid match: (StarTree(DotTree(Leaf('1'), Leaf('1'))), '111')\n"}, "test_regex_match.TestRegexMatch.test_bar_fail": {"description": "Correctly rejects near-bars?", "message": "True is not false : Accepts invalid match: (BarTree(Leaf('1'), Leaf('2')), '')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_regex_match.py\", line 78, in test_bar_fail\n    \"Accepts invalid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid match: (BarTree(Leaf('1'), Leaf('2')), '')\n"}, "test_regex_match.TestRegexMatch.test_bar_star_dot_fail": {"description": "Correctly rejects near bar-star-dots?", "message": "True is not false : Accepts invalid match: (StarTree(StarTree(Leaf('2'))), '2 2222')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_regex_match.py\", line 167, in test_bar_star_dot_fail\n    \"Accepts invalid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid match: (StarTree(StarTree(Leaf('2'))), '2 2222')\n"}, "test_regex_match.TestRegexMatch.test_bar_okay": {"description": "Correctly matches barred regexes?", "message": "False is not true : Rejects valid match: (BarTree(Leaf('e'), Leaf('2')), '2')", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_regex_match.py\", line 70, in test_bar_okay\n    \"Rejects valid match: {}\".format(t))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid match: (BarTree(Leaf('e'), Leaf('2')), '2')\n"}}}, "test_is_regex.TestIsRegex": {"passes": {"test_is_regex.TestIsRegex.test_dot": "Dot regexes accepted?", "test_is_regex.TestIsRegex.test_bar": "Bar regexes accepted?", "test_is_regex.TestIsRegex.test_leaf_ok": "Leaf regular expressions accepted?", "test_is_regex.TestIsRegex.test_bar_star_dot_ok": "Bar-star-dot regexes accepted?", "test_is_regex.TestIsRegex.test_bar_dot_ok": "Bar-dot regexes accepted?"}, "failures": {"test_is_regex.TestIsRegex.test_star_ok": {"description": "Star regexes accepted?", "message": "False is not true : Rejects valid regex: e*", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_is_regex.py\", line 66, in test_star_ok\n    \"Rejects valid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid regex: e*\n"}, "test_is_regex.TestIsRegex.test_bar_star_dot_fail": {"description": "Bar-star-dot non-regexes rejected?", "message": "True is not false : Accepts invalid regex: 0*|1.2", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_is_regex.py\", line 137, in test_bar_star_dot_fail\n    \"Accepts invalid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid regex: 0*|1.2\n"}, "test_is_regex.TestIsRegex.test_dot_fail": {"description": "Dot-like non-regexes rejected?", "message": "True is not false : Accepts invalid regex: 0.1", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_is_regex.py\", line 59, in test_dot_fail\n    \"Accepts invalid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid regex: 0.1\n"}, "test_is_regex.TestIsRegex.test_dot_star_ok": {"description": "Dot-star regexes accepted?", "message": "False is not true : Rejects valid regex: (0.(1.2*))*", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_is_regex.py\", line 112, in test_dot_star_ok\n    \"Rejects valid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid regex: (0.(1.2*))*\n"}, "test_is_regex.TestIsRegex.test_leaf_fail": {"description": "Leaf non-regexes rejected?", "message": "True is not false : Accepts invalid regex: (1)", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_is_regex.py\", line 31, in test_leaf_fail\n    \"Accepts invalid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid regex: (1)\n"}, "test_is_regex.TestIsRegex.test_dot_star_fail": {"description": "Dot-star-like non-regexes rejected?", "message": "True is not false : Accepts invalid regex: 0.1*", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_is_regex.py\", line 119, in test_dot_star_fail\n    \"Accepts invalid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid regex: 0.1*\n"}, "test_is_regex.TestIsRegex.test_star_fail": {"description": "Star-like non-regexes rejected?", "message": "True is not false : Accepts invalid regex: (2*)", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_is_regex.py\", line 73, in test_star_fail\n    \"Accepts invalid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid regex: (2*)\n"}, "test_is_regex.TestIsRegex.test_bar_fail": {"description": "Bar-like non-regexes rejected?", "message": "True is not false : Accepts invalid regex: 0|1", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_is_regex.py\", line 45, in test_bar_fail\n    \"Accepts invalid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid regex: 0|1\n"}, "test_is_regex.TestIsRegex.test_bar_star_fail": {"description": "Bar-star-like non-regexes rejected?", "message": "True is not false : Accepts invalid regex: 0|1*", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_is_regex.py\", line 104, in test_bar_star_fail\n    \"Accepts invalid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid regex: 0|1*\n"}, "test_is_regex.TestIsRegex.test_bar_star_ok": {"description": "Bar-star regexes accepted?", "message": "False is not true : Rejects valid regex: (0|(1|2*))*", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_is_regex.py\", line 97, in test_bar_star_ok\n    \"Rejects valid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 654, in assertTrue\n    raise self.failureException(msg)\n\nAssertionError: False is not true : Rejects valid regex: (0|(1|2*))*\n"}, "test_is_regex.TestIsRegex.test_bar_dot_fail": {"description": "Bar-dot-line non-regexes rejected?", "message": "True is not false : Accepts invalid regex: (0.1|2.e)", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_is_regex.py\", line 89, in test_bar_dot_fail\n    \"Accepts invalid regex: {}\".format(r))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 648, in assertFalse\n    raise self.failureException(msg)\n\nAssertionError: True is not false : Accepts invalid regex: (0.1|2.e)\n"}}}, "test_build_regex_tree.TestBuildRegexTree": {"passes": {"test_build_regex_tree.TestBuildRegexTree.test_bar": "Correctly builds bar trees?", "test_build_regex_tree.TestBuildRegexTree.test_dot": "Correctly builds dot trees?"}, "errors": {"test_build_regex_tree.TestBuildRegexTree.test_leaf": {"description": "Correctly builds leaves?", "message": "string index out of range", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_build_regex_tree.py\", line 23, in test_leaf\n    self.assertEqual(t[0], build_regex_tree(t[1]),\n\n  File \"/home/a08test/submissions/ahmadar2/a2/regex_functions.py\", line 164, in build_regex_tree\n    if regex_list[0][1][-1] == '*':\n\nIndexError: string index out of range\n"}, "test_build_regex_tree.TestBuildRegexTree.test_star": {"description": "Correctly builds star trees?", "message": "string index out of range", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_build_regex_tree.py\", line 49, in test_star\n    self.assertEqual(t[0], build_regex_tree(t[1]),\n\n  File \"/home/a08test/submissions/ahmadar2/a2/regex_functions.py\", line 164, in build_regex_tree\n    if regex_list[0][1][-1] == '*':\n\nIndexError: string index out of range\n"}}, "failures": {"test_build_regex_tree.TestBuildRegexTree.test_bar_dot": {"description": "Correctly builds bar-dot trees?", "message": "BarTree(DotTree(Leaf('0'), Leaf('1')), DotTree(Leaf('2'), Leaf('e'))) != BarTree(Leaf(['0', '1']), Leaf('.')) : Regex tree BarTree(DotTree(Leaf('0'), Leaf('1')), DotTree(Leaf('2'), Leaf('e'))) doesn't match ((0.1)|(2.e)).", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/home/a08test/submissions/ahmadar2/a2/test_build_regex_tree.py\", line 66, in test_bar_dot\n    t[0], t[1]))\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 797, in assertEqual\n    assertion_func(first, second, msg=msg)\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 790, in _baseAssertEqual\n    raise self.failureException(msg)\n\nAssertionError: BarTree(DotTree(Leaf('0'), Leaf('1')), DotTree(Leaf('2'), Leaf('e'))) != BarTree(Leaf(['0', '1']), Leaf('.')) : Regex tree BarTree(DotTree(Leaf('0'), Leaf('1')), DotTree(Leaf('2'), Leaf('e'))) doesn't match ((0.1)|(2.e)).\n"}}}}, "date": "2016-04-01T02:39:24"}